// Auto-generated stub exports
export const ChatMessage: any = undefined as any;
export type ChatMessage = any;
export const DEFAULT_OPENROUTER_FREE_MODEL: any = undefined as any;
export type DEFAULT_OPENROUTER_FREE_MODEL = any;
export const IAgent: any = undefined as any;
export type IAgent = any;
export const LLMService: any = undefined as any;
export type LLMService = any;
export const ModelSelectionRequest: any = undefined as any;
export type ModelSelectionRequest = any;
export const ModelSelector: any = undefined as any;
export type ModelSelector = any;
export const QuotaConfig: any = undefined as any;
export type QuotaConfig = any;
export const QuotaService: any = undefined as any;
export type QuotaService = any;
export const SelectedModel: any = undefined as any;
export type SelectedModel = any;
